### PR TITLE
fix: Backward compatible unocss dependent version，close #3;

### LINKED ISSUE #3: dependencies need update
WARN  Issues with peer dependencies found
.
└─┬ unocss-preset-autoprefixer 0.0.5
  └── ✕ unmet peer unocss@^0.45.5: found 0.50.0

### PR DESCRIPTION
**Pull request by markthree**
We should implement version backward compatibility for peer dependencies such as unocsc, which will make NPM downloads more user-friendly.

Related issues: #3

### CODE REVIEW

**Comment by markthree** [comment]
The current NPM download of this package may result in an error due to conflicting versions of peer dependencies
image

This PR has fixed this issue

**Comment by zouhangwithsweet** [comment]
How about use **pnpm** as pkg manager ? :)

**Comment by markthree** [comment]
> How about use **pnpm** as pkg manager ? :)

PNPM is very nice, but we cannot guarantee that users will always use PNPM as a package manager. If the other party uses NPM, they are not particularly proficient in the dependency relationships of the package. To some extent, this will lead them to directly give up using the package

**Comment by markthree** [comment]
> How about use **pnpm** as pkg manager ? :)

And even if we use pnpm, we will receive warnings。

image

**Comment by zouhangwithsweet** [comment]
Yeah, I found that there is `package-lock.json` file in this pr. I mean in this repo we should use `pnpm` to generate `pnpm-lock.yaml`

**Comment by markthree** [comment]
> Yeah, I found that there is `package-lock.json` file in this pr. I mean in this repo we should use `pnpm` to generate `pnpm-lock.yaml`

Sorry, I misunderstood your meaning. Github's online code added package lock.json for me, and I will resubmit

**Comment by markthree** [comment]
Updated，This time it should be okay 🤣

**Pull request merged**
